Repository Eventiva/Eventiva, pull requests merged in 2024-02, with the labels that each got.

#304 chore: release develop
  .release-please-manifest.json
  CHANGELOG.md
  package.json
  projects/workflows/bit/todo/packages/workflows/bit/todo/CHANGELOG.md
  projects/workflows/discord/env/packages/workflows/discord/env/CHANGELOG.md
  projects/workflows/discord/generator/packages/workflows/discord/generator/CHANGELOG.md
  projects/workflows/git-subrepo/packages/workflows/git-subrepo/CHANGELOG.md
Labels: Type - Chore, Size - M, Enhancement, Review effort [1-5]: 1, autorelease: pending

#415 chore(develop): release workflows/git-subrepo 0.1.0
  .release-please-manifest.json
  projects/workflows/git-subrepo/CHANGELOG.md
  projects/workflows/git-subrepo/version.txt
Labels: autorelease: pending

#414 chore(develop): release workflows/generator 1.0.0
  .release-please-manifest.json
  projects/workflows/generator/CHANGELOG.md
  projects/workflows/generator/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#420 chore(develop): release eventiva 0.1.1
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: Type - Chore, Size - S, autorelease: pending

#428 chore(main): release eventiva 0.1.2
  .release-please-manifest.json
  CHANGELOG.md
  package.json
Labels: autorelease: pending

#429 chore(main): release bots/discord 0.1.1
  .release-please-manifest.json
  projects/bots/aspects/discordjs/CHANGELOG.md
  projects/bots/aspects/discordjs/version.txt
Labels: autorelease: pending

#430 chore(main): release bots/logging 0.1.1
  .release-please-manifest.json
  projects/bots/aspects/logging/CHANGELOG.md
  projects/bots/aspects/logging/version.txt
Labels: autorelease: pending

#431 chore(main): release workflows/discord/generator 0.1.1
  .release-please-manifest.json
  projects/workflows/discord/generator/module/CHANGELOG.md
  projects/workflows/discord/generator/module/version.txt
Labels: autorelease: pending

#432 chore(main): release workflows/generator 0.1.1
  .release-please-manifest.json
  projects/workflows/generator/CHANGELOG.md
  projects/workflows/generator/version.txt
Labels: autorelease: pending

#440 chore(develop): release workflows/generator 0.1.1
  .release-please-manifest.json
  projects/workflows/generator/CHANGELOG.md
  projects/workflows/generator/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#449 Fix: build steps
  package.json
  pnpm-lock.yaml
  projects/bots/aspects/discordjs/command.ts
  projects/bots/aspects/discordjs/discordjs.node.runtime.ts
  projects/bots/aspects/i18n/index.ts
  projects/bots/aspects/logging/logger.ts
  projects/bots/aspects/logging/logging.node.runtime.ts
  projects/bots/aspects/support-platform/support-platform-app.tsx
Labels: Type - Fix, Size - XXL

#450 chore(main): release eventiva 0.1.3
  .github/releases/.release-main-manifest.json
  CHANGELOG.md
  package.json
Labels: Type - Chore, Size - S, autorelease: pending

#452 chore(main): release bots/i18n 0.1.1
  .release-please-manifest.json
  projects/bots/aspects/i18n/CHANGELOG.md
  projects/bots/aspects/i18n/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#454 chore(main): release discord/platforms/support 0.1.1
  .release-please-manifest.json
  projects/bots/aspects/support-platform/CHANGELOG.md
  projects/bots/aspects/support-platform/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#453 chore(main): release bots/logging 0.1.2
  .release-please-manifest.json
  projects/bots/aspects/logging/CHANGELOG.md
  projects/bots/aspects/logging/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#457 chore(main): release bots/i18n 0.1.1
  .github/releases/.release-main-manifest.json
  projects/bots/aspects/i18n/CHANGELOG.md
Labels: Type - Chore, Size - XS, autorelease: pending

#458 chore(main): release discord/platforms/support 0.1.1
  .github/releases/.release-main-manifest.json
Labels: Type - Chore, Size - XS, autorelease: pending

#509 chore(main): release eventiva 0.1.4
  .github/releases/.release-main-manifest.json
  CHANGELOG.md
  package.json
Labels: Type - Chore, Size - S, autorelease: pending

#510 chore(main): release bots/discord 0.1.3
  .github/releases/.release-main-manifest.json
  projects/bots/aspects/discordjs/CHANGELOG.md
  projects/bots/aspects/discordjs/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#512 chore(main): release bots/logging 0.1.2
  .github/releases/.release-main-manifest.json
  projects/bots/aspects/logging/CHANGELOG.md
Labels: Type - Chore, Size - XS, autorelease: pending

#513 chore(main): release discord/platforms/support 0.1.2
  .github/releases/.release-main-manifest.json
  projects/bots/aspects/support-platform/CHANGELOG.md
  projects/bots/aspects/support-platform/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#511 chore(main): release bots/i18n 0.1.2
  .github/releases/.release-main-manifest.json
  projects/bots/aspects/i18n/CHANGELOG.md
  projects/bots/aspects/i18n/version.txt
Labels: Type - Chore, Size - S, autorelease: pending

#517 chore(codeql.yml): add support for triggering workflows on merge_group
  .github/workflows/codeql.yml
  .github/workflows/management-github_management.yml
  .github/workflows/security-defender-for-devops.yml
  .github/workflows/security-dependency-review.yml
  .github/workflows/security-ossar.yml
  .github/workflows/security-secrets.yml
  .github/workflows/security-snyk.yml
Labels: Type - Chore, Size - M

#518 chore(main): release bots/logging 0.1.3
  .github/releases/.release-main-manifest.json
  projects/bots/aspects/logging/CHANGELOG.md
  projects/bots/aspects/logging/version.txt
Labels: Type - Chore, Size - XS, autorelease: pending

#531 chore(management-changelog.yml): temporarily disable triggering workflow
  .github/workflows/management-changelog.yml
Labels: Type - Chore, Size - XS

#533 chore(workspace.jsonc): enable workspace variants and add package configuration for teambit.pkg/pkg
  .github/workflows/chore-trunk-nightly.yml
  .github/workflows/components-bit-init.yml
  .github/workflows/components-branch-lane.yml
  .github/workflows/components-commit-bitmap.yml
  .github/workflows/components-dependency-update.yml
  .github/workflows/components-lane-cleanup.yml
  .github/workflows/components-pull-request.yml
  .github/workflows/components-tag-export.yml
  .github/workflows/components-verify.yml
  .github/workflows/management-changelog.yml
  workspace.jsonc
Labels: Type - Chore, Size - M

#535 Fix: bit tag method
  .github/workflows/chore-subrepo-pull.yml
  .github/workflows/chore-subrepo-push.yml
  .github/workflows/management-changelog.yml
Labels: Type - Fix, Size - S

#525 chore(main): release eventiva 0.1.5
  .github/releases/.release-manifest.json
  CHANGELOG.md
  package.json
Labels: Type - Chore, Size - S, autorelease: pending

#534 chore(security-dependency-review.yml): remove unnecessary push event branches to improve workflow efficiency
  .github/workflows/security-dependency-review.yml
Labels: Type - Chore, Size - XS
